[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
bytecode_hash = "none"
cbor_metadata = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1_000

[invariant]
runs = 256
depth = 64
fail_on_revert = false
